### ISSUE TITLE
dstask just killed on every command

### ISSUE THREAD

**Issue by Zejnilovic** [naggie/dstask#7] opened 2019-09-26 15:46 UTC
I wanted to try the tool. But I am not able to even print help.

I did:
0. Download appropriate release for:
```
╭─me@myPC ~/path/to/dstask
╰─$ uname -s
Darwin
```
1. `cp ~/Downloads/dstask-darwin-amd64 /usr/local/bin/dstask`
2. `chmod +x /usr/local/bin/dstask`
3. run `dstask help`
4. get info it is killed
```
╭─me@myPC ~/path/to/dstask
╰─$ dstask help
[1]    20642 killed     dstask help
```

Could you point me in the right direction?

**Comment by naggie** [comment] 2019-09-26 16:01
Quite right -- sorry I think there is an issue with cross-compliation. I've recompiled the binary and replaced the release. Please re-download it.

**Comment by naggie** [comment] 2019-09-26 16:06
This looks like the cause: https://github.com/upx/upx/issues/222 

I'll add a UPX version check or something. Thanks for reporting!

**Comment by Zejnilovic** [comment] 2019-09-26 16:14
Cool, I have time, I am just picking up projects to look at for fun.

**Comment by naggie** [comment] 2019-09-26 16:28
Yes -- you'll need to initialise a git repository with `mkdir ~/.dstask && git -C ~/.dstask init`. I think I'll add that to the error message -- I could make dstask automatically create the repo too, though I've avoided that in case it confuses someone who has a repo on github (or whatever) already... I'll reconsider, as the out of the box experience is important!

Personally I have a script to clone my existing dstask repository from github in my dotfiles setup script https://github.com/naggie/dotfiles/blob/master/user-configuration-naggie.sh#L169

**Comment by Zejnilovic** [comment] 2019-09-26 16:35
I didn't want to bother you with that. I just printed the message as I think it "works". I like the message. The `""` are there because every software has 1 redundant instruction and 1 instruction that is wrong.

But if we are talking about the out of the box experience. Just a question "Do you want to init a new taks repo" should be plenty.

**Comment by naggie** [comment] 2019-09-26 19:04
> I didn't want to bother you with that.
I'm not bothered, it's useful to see what users experience.

Good idea -- a question/prompt is the right solution that prevents clobbering yet still allows for a good out of box experience. I've created https://github.com/naggie/dstask/issues/8 to track it 

I've also disabled UPX for macos executables, so I'll close this issue.

**Closed** 2019-09-26 19:15 UTC
